import eslint from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import globals from "globals";
import tseslint from "typescript-eslint";

// Generated by `wxt prepare` (runs on postinstall).
const autoImports = await import("./.wxt/eslint-auto-imports.mjs").then(
    (m) => m.default,
    () => null,
);

export default defineConfig([
    ...(autoImports ? [autoImports] : []),
    eslint.configs.recommended,
    tseslint.configs.recommended,
    eslintConfigPrettier,
    globalIgnores([".wxt/", ".output/", "**/*.d.ts"]),
    {
        plugins: {
            "simple-import-sort": simpleImportSort,
        },
        rules: {
            "simple-import-sort/imports": "error",
            "simple-import-sort/exports": "error",
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    varsIgnorePattern: "^_+$",
                    argsIgnorePattern: "^_+$",
                    caughtErrorsIgnorePattern: "^_+$",
                },
            ],
        },
        languageOptions: {
            globals: {
                ...globals.browser,
                chrome: "readonly",
            },
        },
    },
    {
        files: ["*.js", "*.ts", "tests/**"],
        languageOptions: {
            globals: {
                ...globals.node,
            },
        },
    },
]);
